version: "3"

services:
  tracker:
    build: .
    depends_on:
      - postgres
    ports:
      - "3005:3005"

  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=time-tracker-prod
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local